### ISSUE TITLE
Always getting `0` back fron ->check

### ISSUE THREAD

**Issue by nathan-fiscaletti** [touhonoob/RateLimit#15]
I've tried creating a rate limit that only allows 1 request every 5 seconds, but i seem to always get `0` back from `->check(`.

I have `php-apcu` installed and am using php-7.1.

My Code:

```php
<?php

require 'vendor/autoload.php';

use \Touhonoob\RateLimit\RateLimit;
use \Touhonoob\RateLimit\Adapter\APCu as RateLimitAdapterAPCu;

$adapter = new RateLimitAdapterAPCu(); // Use APCu as Storage
$rateLimit = new RateLimit("myratelimit", 1, 5, $adapter); // 1 Requests / 5 seconds

$id = $_SERVER['REMOTE_ADDR']; // Use client IP as identity
if ($rateLimit->check($id) > 0) { // This always returns 0 so it's always exceeded?
  echo "passed";
} else {
  echo "rate limit exceeded";
}
```

**Comment by nathan-fiscaletti** [comment]
I've verified it works kind of strange. 

I can get `5 requests per 1 second` to work, but if i try something like `10 requests per 20 seconds` after a few requests (not even 20) it seems to decide I've exceeded the limit.

**Comment by DavidGoodwin** [comment]
I can't reproduce this in my fork of this project - I have some hazy memory of hitting this problem but I can't find a changeset to pin it to. 

( https://github.com/DavidGoodwin/RateLimit/blob/master/src/RateLimit.php#L57 )

**Comment by nathan-fiscaletti** [comment]
Could it possibly have something to do with using integers instead of floats? @DavidGoodwin

**Comment by DavidGoodwin** [comment]
Without looking properly (I'm at work) I know I changed the RateLimit::check() in my fork to return a boolean; rather than an integer.

https://github.com/touhonoob/RateLimit/blob/master/src/RateLimit.php#L58

https://github.com/DavidGoodwin/RateLimit/blob/master/src/RateLimit.php#L57

**Comment by nathan-fiscaletti** [comment]
Any update on this?

**Comment by DavidGoodwin** [comment]
https://packagist.org/packages/palepurple/rate-limit :)

**Comment by touhonoob** [comment]
thanks to @DavidGoodwin
